// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrqkbjvcsjgdtzgwepqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycWtianZjc2pnZHR6Z3dlcHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzQyNjMsImV4cCI6MjA2NTkxMDI2M30.Wsql2fmDvxaBfvlEgj8XHngzz_rtlUf8hCVwA2_1y_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);